### ISSUE TITLE
Clear cache when a Stack is updated (version change)

### ISSUE THREAD

**Issue by Frzk** [Scalingo/apt-buildpack#8]
Currently, the buildpack has logic to clear the apt cache when the `Aptfile` has changed, or when the Stack has changed.
But I think it should also clear it when the Stack **version** has changed (we often see issues on support when a Stack update occurs).

The main issue is that the version of the stack doesn't seem to be exposed, or is it?

**Comment by EtienneM** [comment]
> The main issue is that the version of the stack doesn't seem to be exposed, or is it?

I confirm that the version of the stack is not exposed. The only stack-related thing exposed is inside the `STACK` environment variable and it's the stack name (e.g. `scalingo-22`). 

Hence this ticket cannot be tackled. We could imagine an internal ticket to add the stack version in another environment variable, but it is out of the scope of this ticket.

**Comment by john-scalingo** [comment]
Apt is able to manage its own cache without any issue. There's no need to clear the cache on minor version release.

The issue lies in the scalingo-builder-runner (https://github.com/Scalingo/scalingo-builder-runner/issues/295) with this bug Apt thinks that its cache is always up to date which lead to the issue seen on the support.
